services:
  searcharr:
    container_name: searcharr
    build:
      context: .
    image: searcharr-local:2.0.0
    pull_policy: never
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./settings.py:/app/settings.py
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    networks:
      - bronet

networks:
  bronet:
    external: true
    name: bronet
