version: '3.0'
services:
  searcharr:
    container_name: searcharr
    build:
      context: .
    image: cheilia77-sketch/searcharr:local
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./settings.py:/app/settings.py
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    networks:
      - arr_bridge
